### ISSUE TITLE
generate fails (SSG)

### ISSUE THREAD

**Issue by PhE** [nuxt-ui-pro/saas#14]
The `generate` script raises an error:

```
> npx pnpm run generate
[..]
  │ └── Linked from /blog/v3-8
  ├─ /docs/api/composables/use-async-data (620ms)                                                                                                       nitro 2:16:40 PM
  │ ├── Error: [404] Page not found
  │ └── Linked from /blog/v3-8
  ├─ /docs/guide/directory-structure/node_modules (637ms)                                                                                               nitro 2:16:40 PM
  │ ├── Error: [404] Page not found
  │ └── Linked from /blog/v3-8
  ├─ /docs/guide/going-further/nightly-release-channel (637ms)                                                                                          nitro 2:16:40 PM
  │ ├── Error: [404] Page not found
  │ └── Linked from /blog/v3-8
                                                                                                                                                        nitro 2:16:40 PM

 ERROR  Exiting due to prerender errors.                                                                                                                      2:16:40 PM

  at prerender (node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.0a84349b.mjs:216:11)
  at async node_modules/.pnpm/nuxt@3.10.1_eslint@8.56.0_typescript@5.3.3_vite@5.0.12_vue-tsc@1.8.27/node_modules/nuxt/dist/index.mjs:3299:7
  at async build (node_modules/.pnpm/nuxt@3.10.1_eslint@8.56.0_typescript@5.3.3_vite@5.0.12_vue-tsc@1.8.27/node_modules/nuxt/dist/index.mjs:4767:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/build.mjs:98:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/generate.mjs:59:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7) 



 ERROR  Exiting due to prerender errors.                                                                                                                      2:16:40 PM

 ELIFECYCLE  Command failed with exit code 1.
```

Is seems obvious the sample docs and blog pages contains dead links.

I could fix those basic issues with a PR.
Will you merge it ?

**Comment by benjamincanac** [comment]
This will be fixed by #12 already. We're gonna merge it soon 😊

**Comment by benjamincanac** [comment]
Should be good now 👍

**Comment by PhE** [comment]
It works.
Thanks !
