### ISSUE TITLE
ERROR  The URL must be of scheme file 

### ISSUE THREAD

**Issue by yxw007** [nuxt-ui-pro/saas#54]
# System 
- win10

# Steps to Reproduction
1. git clone [git@github.com:yxw007/nuxt_saas.git](https://github.com/yxw007/nuxt_saas.git)
2. pnpm i

output:
```bash
$ pnpm i
Lockfile is up to date, resolution step is skipped
Already up to date

> nuxt-ui-pro-template-saas@ postinstall D:\Work\Projects\nuxt_saas
> nuxt prepare

ℹ Using default Tailwind CSS file                                 nuxt:tailwindcss 09:35:08
ℹ Nuxt Icon server bundle mode is set to local                                     09:35:11
[09:35:12] ✔ Nuxt Icon discovered local-installed 3 collections: heroicons, simple-icons, vscode-icons
ℹ Running with compatibility version 4                                             09:35:12

 ERROR  The URL must be of scheme file                                              09:35:13

  at fileURLToPath (node:internal/url:1491:11)
  at fileURLToPath (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:1971:25)
  at pathToFileURL (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:1974:26)
  at _resolve (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2108:10)
  at resolveSync (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2111:10)
  at resolvePathSync (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2121:24)
  at useComponentMetaParser (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/nuxt-component-meta@0.8.2_magicast@0.3.5_rollup@4.22.2/node_modules/nuxt-component-meta/dist/parser.mjs:44:22)
  at /D:/Work/Projects/nuxt_saas/node_modules/.pnpm/nuxt-component-meta@0.8.2_magicast@0.3.5_rollup@4.22.2/node_modules/nuxt-component-meta/dist/module.mjs:184:16
  at async /D:/Work/Projects/nuxt_saas/node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_eslint@9.10.0_jiti@1.21.6__ioredis@5.4.1_uj7xazh3ekc62ulknauwwjfwmm/node_modules/nuxt/dist/index.mjs:2385:7
  at async generateApp (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_eslint@9.10.0_jiti@1.21.6__ioredis@5.4.1_uj7xazh3ekc62ulknauwwjfwmm/node_modules/nuxt/dist/index.mjs:5250:3)
  at async _applyPromised (/D:/Work/Projects/nuxt_saas/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:10) 
```

# More info
- node version: v22.3.0
- pnpm version: 9.9.0

**Comment by yxw007** [comment]
![6GP7SOT8R%B}V88}}~ZGZ}O](https://github.com/user-attachments/assets/1e51e959-4bcd-4c93-b2a6-9d3a4f711e89)

After debugging, it was found that the default export path of this icon was missing .js.

**Comment by justserdar** [comment]
I encounter the same issue on win10, simply cloning and installing the project will result in:  The URL must be of scheme file.
A fix is also PR'd, any idea when this will get through?

**Comment by yxw007** [comment]
> I encounter the same issue on win10, simply cloning and installing the project will result in:  The URL must be of scheme file.
> 
> A fix is also PR'd by OP, any idea when this will get through?
> 
> 

Actually I don't know😂, I tried to leave a message to the maintainer on X to see if I could speed up this pr process

**Comment by larbish** [comment]
`nuxt/icon` has been released: https://github.com/nuxt/icon/releases/tag/v1.5.3 

Can you confirm it fixes the issue?

**Comment by justserdar** [comment]
Installing @nuxt.icon locally in the template updates it too version 1.5.3, building now finishes.
Once nuxt-ui updates the nuxt-icon package to 1.5.3 also then itll fix it for everybody using the template.

Temp fix by installing locally: 
npx nuxi module add icon

**Comment by yxw007** [comment]
> @larbish @yxw007 
> 
> Installing locally in the template updates(overrides current package version) too version 1.5.3, install & build now finishes succesfully, the PR fixed it.
> 
> Once Nuxt-ui (auto-imports nuxt/icon) also updates the nuxt-icon package to 1.5.3, then itll fix it for everybody using this template.
> 
> 
> 
> **Temp workaround, installing v1.5.3 locally:**
> 
> npx nuxi module add icon

Ok, Thanks for your feedback
